// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Mvc.Data.Models
{
    public partial class Categoria
    {
        public Categoria()
        {
            InverseIdPadreNavigation = new HashSet<Categoria>();
            Productos = new HashSet<Producto>();
        }

        public int Id { get; set; }
        public string Descripcion { get; set; }
        public int? IdPadre { get; set; }

        public virtual Categoria IdPadreNavigation { get; set; }
        public virtual ICollection<Categoria> InverseIdPadreNavigation { get; set; }
        public virtual ICollection<Producto> Productos { get; set; }
    }
}