// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Mvc.Data.Models
{
    public partial class Direccione
    {
        public Direccione()
        {
            Proveedors = new HashSet<Proveedor>();
            Sucursales = new HashSet<Sucursale>();
        }

        public int Id { get; set; }
        public int IdAsentamiento { get; set; }
        public string Calle { get; set; }
        public string Numero { get; set; }

        public virtual CodigosPostale IdAsentamientoNavigation { get; set; }
        public virtual ICollection<Proveedor> Proveedors { get; set; }
        public virtual ICollection<Sucursale> Sucursales { get; set; }
    }
}