// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Mvc.Data.Models
{
    public partial class Municipio
    {
        public Municipio()
        {
            CodigosPostales = new HashSet<CodigosPostale>();
        }

        public int Id { get; set; }
        public int IdEstado { get; set; }
        public int Cve { get; set; }
        public string Municipio1 { get; set; }

        public virtual Estado IdEstadoNavigation { get; set; }
        public virtual ICollection<CodigosPostale> CodigosPostales { get; set; }
    }
}