// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Mvc.Data.Models
{
    public partial class Ocasione
    {
        public Ocasione()
        {
            ProductoOcasiones = new HashSet<ProductoOcasione>();
        }

        public int Id { get; set; }
        public string Ocasion { get; set; }

        public virtual ICollection<ProductoOcasione> ProductoOcasiones { get; set; }
    }
}