// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Mvc.Data.Models
{
    public partial class Proveedor
    {
        public Proveedor()
        {
            Productos = new HashSet<Producto>();
        }

        public int Id { get; set; }
        public string Proveedor1 { get; set; }
        public int? IdDireccion { get; set; }

        public virtual Direccione IdDireccionNavigation { get; set; }
        public virtual ICollection<Producto> Productos { get; set; }
    }
}