// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Mvc.Data.Models
{
    public partial class Usuario
    {
        public Usuario()
        {
            UsuarioRols = new HashSet<UsuarioRol>();
        }

        public int Id { get; set; }
        public string Login { get; set; }
        public string Email { get; set; }
        public string Telefono { get; set; }
        public string Password { get; set; }

        public virtual ICollection<UsuarioRol> UsuarioRols { get; set; }
    }
}